### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [DrArzter/oop-put-course#1]
**Task 1**
- [x] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Rename file to task1.cpp
- [x] Format code [properly](https://google.github.io/styleguide/cppguide.html) e.g. different classes use different naming convention
- [x] Comments like `/* in kilograms */` doesn't mean anything :/ better remove it or add unit of measure verification
- [x] Fields like `int add_fuel` don't seem neither reasonably nor naturally
